scripts/dtc: Update to upstream version v1.4.6 (DTC overlay support)
Backport DTC 1.4.6-9-gaadd0b65c987 from lineage-20 (previously on
1.4.4-g756ffc4f) to fix building DTBO overlays. DTC 1.4.4 fails to
parse '&label { }' overlay syntax used in sdmmagpie-thermal-overlay.dtsi:

  Error: sdmmagpie-thermal-overlay.dtsi:15.1-15 syntax error
  FATAL ERROR: Unable to parse input tree

Also carries the integer overflow checks in the fdt header
(3040709f2223).