Revert "cpufreq: Remove duplicate to_gov_attr_set() definition"
Commit 61adf51bafb8 ("cpufreq: Remove duplicate to_gov_attr_set()")
claimed the helper was defined elsewhere, but no other definition
exists: include/linux/cpufreq.h only declares struct gov_attr_set and
cpufreq_governor.h never provided the helper either.

This broke the build:

  ../drivers/cpufreq/cpufreq_governor_attr_set.c:25:21: error:
    implicit declaration of function 'to_gov_attr_set'
    [-Werror,-Wimplicit-function-declaration]
  ../drivers/cpufreq/cpufreq_governor_attr_set.c:25:21: error:
    incompatible integer to pointer conversion passing 'int' to
    parameter of type 'struct gov_attr_set *' [-Wint-conversion]
  ../drivers/cpufreq/cpufreq_governor_attr_set.c:31:34: error:
    implicit declaration of function 'to_gov_attr_set'
    [-Werror,-Wimplicit-function-declaration]
  ../drivers/cpufreq/cpufreq_governor_attr_set.c:31:23: error:
    incompatible integer to pointer conversion initializing
    'struct gov_attr_set *' with an expression of type 'int'
    [-Wint-conversion]

Restore the static inline definition. Both call sites (governor_show()
and governor_store()) are in this translation unit only, so a static
helper here is correct and no header change is needed.

Signed-off-by: ardia-kun <ardiayogabekti@gmail.com>