Reapply "ANDROID: HACK: arm64, LLVMLinux: use -mno-implicit-float"
This reverts commit 59f24c4046f73d88ccb87ed62c70304bc1eaebe6.
Looks like full xiaomi drm import needs this

ld.lld errors with clang:

ld.lld: error: undefined symbol: __floatunsisf
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o

ld.lld: error: undefined symbol: __mulsf3
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o

ld.lld: error: undefined symbol: __extendsfdf2
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o

ld.lld: error: undefined symbol: __adddf3
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o

ld.lld: error: undefined symbol: __fixdfsi
>>> referenced by dsi_panel.c:1049 (/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:1049)
>>>               drivers/gpu/drm/msm/dsi-staging/dsi_panel.o:(dc_set_backlight) in archive built-in.o

and gcc telling us the actual culprit:
/run/host/run/media/vbajs/Data/los-perf-kernel_xiaomi_sm6150/drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:994:26: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types

Signed-off-by: ardia-kun <ardiayogabekti@gmail.com>